name: AutoReleaser

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.24.3
      -
        run: cd ${{ github.workspace }}/.. && wget https://raw.githubusercontent.com/ItsIgnacioPortal/hacker-scoper/main/.github/.goreleaser.yml && pwd
      -
        name: run GoReleaser
        uses: goreleaser/goreleaser-action@v6.3.0
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          # 'latest', 'nightly', or a semver
          version: '~> v2'
          args: release --clean --config ${{ github.workspace }}/../.goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  chocolatey:
    needs: goreleaser
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Run powershell script
        run: |
          powershell -ep bypass .\.github\autoreleaser-helper.ps1
      -
        name: Create Choco pack
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: pack choco\hacker-scoper\hacker-scoper.nuspec
      - 
        name: Upload to chocolatey
        run: |
          FOR /F "tokens=* USEBACKQ" %%F IN (`dir /B *.nupkg`) DO (SET filename=%%F)
          ECHO %filename%
          choco push %filename% --source "'https://push.chocolatey.org/'" --api-key "'${{ secrets.CHOCOLATEY_API_KEY }}'"
