name: AutoReleaser

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*.*.*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      -
        name: set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.24.3
      -
        run: cd ${{ github.workspace }}/.. && wget https://raw.githubusercontent.com/ItsIgnacioPortal/hacker-scoper/main/.github/.goreleaser.yml && pwd
      -
        name: run GoReleaser
        uses: goreleaser/goreleaser-action@v2.9.0
        with:
          version: latest
          args: release --clean --config ${{ github.workspace }}/../.goreleaser.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUBTOKEN }}

  chocolatey:
    needs: goreleaser
    runs-on: windows-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      -
        name: Run powershell script
        run: |
          powershell -ep bypass .\.github\autoreleaser-helper.ps1
      -
        name: Create Choco pack
        uses: crazy-max/ghaction-chocolatey@v2
        with:
          args: pack choco\hacker-scoper\hacker-scoper.nuspec
